# Generated by Django 4.0.4 on 2022-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treinamento', models.DateTimeField()),
                ('total_imagens', models.IntegerField()),
            ],
        ),
    ]
