# Generated by Django 4.0.4 on 2022-05-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_motorista', models.CharField(max_length=100)),
                ('status_passageiro', models.CharField(max_length=100)),
                ('link_imagem', models.CharField(max_length=200)),
                ('data_hora_deteccao', models.DateTimeField()),
            ],
        ),
    ]
