# Generated by Django 4.0.4 on 2022-05-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_deteccao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deteccao',
            table='deteccao',
        ),
        migrations.AlterModelTable(
            name='treinamento',
            table='treinamento',
        ),
    ]
