# Generated by Django 4.0.4 on 2022-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_deteccao_table_alter_treinamento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='data_hora_deteccao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trains',
            name='data_treinamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
