# Generated by Django 4.0.4 on 2022-05-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deteccao_data_hora_deteccao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detections',
        ),
        migrations.DeleteModel(
            name='trains',
        ),
    ]
